_core:
  default_config_hash: e1PekxOlsENErPqF_thc8pLGue7oBm0In_S8cNn-8zQ
content: |+
  # See https://iabtechlab.com/ads-txt-about/
  # < SSP/Exchange Domain >, < SellerAccountID >, < PaymentsType >, < TAGID >
  google.com, pub-2334169882538249, DIRECT, f08c47fec0942fa0

app_content: |+
  # See https://iabtechlab.com/ads-txt-about/
  # < SSP/Exchange Domain >, < SellerAccountID >, < PaymentsType >, < TAGID >
  google.com, pub-2334169882538249, DIRECT, f08c47fec0942fa0

