_core:
  default_config_hash: DrYt8PcXA0xB3C3L1SvtefnkO5SwUonhY3n4Ld8yun4
entity_type_groups:
  node:
    pagina_homepage:
      basic: basic
      advanced: advanced
separator: ','
tag_trim_method: beforeValue
use_maxlength: true
tag_trim_maxlength:
  metatag_maxlength_title: null
  metatag_maxlength_description: null
  metatag_maxlength_abstract: null
tag_scroll_max_height: ''
tag_trim_end: '|.,-:;/+&([{"'''
